DROP TABLE IF EXISTS Employee;


CREATE TABLE Employee (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id INTEGER REFERENCES business(id) NOT NULL,

    emp_name TEXT NOT NULL,
    emp_skill INTEGER NOT NULL,
    emp_required BOOLEAN DEFAULT false,
    in_time INTEGER DEFAULT 0,
    out_time INTEGER DEFAULT 0

    
    -- pos_name TEXT NOT NULL,
    );
