CREATE TABLE Position (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    business_id INTEGER REFERENCES business(id) NOT NULL,

    pos_name TEXT NOT NULL UNIQUE,
    pos_importance INTEGER NOT NULL,
    pos_skill INTEGER NOT NULL,
    pos_required BOOLEAN DEFAULT false);

